experiment_name: tues_night_big_sweep
trainer:
  limit_train_batches: 100
  max_epochs: 100
  logger:
    - class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: "csv_logs"
model:
  rank: 1
  # nheads: 32
data:
  batch_size: 1  # this is a placeholder
  dataset_class: task.NearestPointDatasetOrthogonal
  # dim: 16
  num_points: 2
  num_queries: 4
  num_workers: 15
optimizer:
  # lr: 0.001
lr_scheduler:
  gamma: .95
