experiment_name: march24_cosine_sweep
trainer:
  limit_train_batches: 100
  max_epochs: 100
  logger:
    - class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: "csv_logs"
model:
  rank: 1
  # nheads: 32
data:
  batch_size: 32  # this is rated up to dim=128, H=16384, num_points=2 num_queries=4
  dataset_class: task.NearestPointDatasetOrthogonal
  # dim: 16
  num_points: 2
  num_queries: 4
  num_workers: 15
optimizer:
  # lr: 0.001
  betas:
    - .9
    - .95
lr_scheduler:
